# -*- coding: utf-8 -*-
"""PoundsToDollars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nAImcHdcwdBGeyRwXks-9TMrInRmrJTS
"""



"""# Python fundamentals- Assignment 1

"""

print("Fathima Najiya")
print("ST1001")
print("fathima@gmail.com")

print("Fathima Najiya\nST1001\nfathima@gmail.com")

num1 = 14
num2 = 7

print(f"{num1} + {num2} = {num1 + num2}")  # Addition
print(f"{num1} - {num2} = {num1 - num2}")  # Subtraction
print(f"{num1} * {num2} = {num1 * num2}")  # Multiplication
print(f"{num1} / {num2} = {num1 / num2}")  # Division

for i in range(1,6):
  print(i)

print("\"SDK\" stands for \"Software Development Kit\", whereas \"IDE\" stands for \"Integrated Development Environment\".")

print("python is an \"awesome\" language.")

print("python\n\t2023")

print('I\'m from Entri.\b')

print("\65")

print("\x65")

print("Entri", "2023", sep="\n")

print(" Entri ","2023", sep="\b")

print("Entri","2023",sep="*",end="\b\b\b\b")

# Defining the variables
num = 23
textnum = "57"
decimal = 98.3

# Printing the types of each variable
print("Type of num:", type(num))
print("Type of textnum:", type(textnum))
print("Type of decimal:", type(decimal))

# Converting textnum to integer and calculating the sum
sum_value = num + int(textnum) + decimal

# Printing the sum and its datatype
print("Sum of variables:", sum_value)

days_in_year = 365  # Number of days in a year (non-leap year)
hours_in_day = 24   # Number of hours in a day
minutes_in_hour = 60  # Number of minutes in an hour

# Calculate the total number of minutes in a year
total_minutes_in_year = days_in_year * hours_in_day * minutes_in_hour

# Printing the statement and result
print("This code calculates the total number of minutes in a year based on the number of days, hours, and minutes in each unit of time.")
print(f"Total minutes in a year: {total_minutes_in_year}")

# Asking the user to enter their name
name = input("Please enter your name: ")

# Outputting the greeting
print(f"Hi {name}, welcome to Python programming :)")

# Asking the user to enter an amount in pounds
pounds = float(input("Please enter amount in pounds: "))

# Assuming the exchange rate is 1 pound = 1.25 dollars
dollars = pounds * 1.25

# Printing the result
print(f"£{pounds} are ${dollars}")

